### ISSUE TITLE
01无法启动项目 wind

### ISSUE THREAD

**Issue by huangchaohua** [arcthur/react-book-examples#34]
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8787
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at Server.setupListenHandle [as _listen2] (net.js:1322:14)
    at listenInCluster (net.js:1370:12)
    at Server.listen (net.js:1466:7)
    at Function.listen (D:\company\project\react-book-examples\01\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (D:\company\project\react-book-examples\01\server.js:25:5)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-book-examples@ start: `cross-env NODE_ENV=development node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-book-examples@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\huang\AppData\Roaming\npm-cache\_logs\2017-09-02T03_30_32_860Z-debug.log

**Comment by devinxiang** [comment]
这个问题，我也遇到了，可以看我提的那个issue解决办法

**Comment by zongwong** [comment]
我也启动不了,怎么还用Python?
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (E:\360Downloads\react-book-examples-master\01\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (E:\360Downloads\react-book-examples-master\01\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at E:\360Downloads\react-book-examples-master\01\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
